version: '2'
services:
  mongo_db:
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
  klov:
    image: anshooarora/klov:1.0.1
    container_name: klov
    depends_on:
      - mongo_db
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://host.docker.internal:27017
    ports:
      - 80:80